env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "6"
  - 8
  - 10
  - "node"
sudo: false
services:
  - redis-server
addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - gcc-4.8
       - g++-4.8
after_script:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
